name: mist # you probably want to 'snapcraft register <name>'
version: 'master' # just for humans, typically '1.2+git' or '1.3.2'
summary: automatic plant watering # 79 char long summary
description: |
  automatic plant watering based on node, koa, and a vue client

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  mist:
    command: mist
    plugs: [network-bind]

parts:
  mist:
    # See 'snapcraft plugins'
    plugin: nodejs
    node-package-manager: yarn
    npm-run: [build]
    source: https://github.com/obedm503/mist.git