name: mist # you probably want to 'snapcraft register <name>'
version: 'master' # just for humans, typically '1.2+git' or '1.3.2'
summary: automatic plant watering # 79 char long summary
description: |
  automatic plant watering based on node, koa, and a vue client

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  mist:
    command: npm start
    plugs: [network-bind]

parts:
  mist:
    # See 'snapcraft plugins'
    plugin: nodejs
    npm-run: [build]
    node-engine: 8.9.1
    source: https://github.com/obedm503/mist.git